name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: chanwit/action-eksctl-kale@master
      with:
        region: ap-southeast-1
        cluster: eks-kubeflow
