name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: chanwit/action-eksctl-kale@v1
      with:
        region: us-east-2
        cluster: kubeflow-test
        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
        awsSecretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
        notebook: titanic_ml_comparision.ipynb
